@echo off
SET DDK_PATH=%1
SET PROJECT_CONFIGURATION_NAME=%2
SET PROJECT_DIR=%3
SET SOLUTION_DIR=%4
SET INTEL_CRT_PATH=%5
call %SOLUTION_DIR%ddk_build.bat  %DDK_PATH% %PROJECT_CONFIGURATION_NAME% %PROJECT_DIR%
mkdir %SOLUTION_DIR%..\lib\%PROJECT_CONFIGURATION_NAME%\i386
lib %INTEL_CRT_PATH%\eh.lib %INTEL_CRT_PATH%\exsup.obj obj%DDKBUILDENV%_wxp_x86\i386\libcpp.obj /out:%SOLUTION_DIR%..\lib\%PROJECT_CONFIGURATION_NAME%\i386\libcppvc7.lib